"""empty message

Revision ID: 2786fd419932
Revises: 0763d677d453
Create Date: 2026-02-03 03:09:07.862644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2786fd419932'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_ticket', sa.Float(), nullable=False),
    sa.Column('loteria', sa.String(length=50), nullable=False),
    sa.Column('fecha_sorteo', sa.String(length=50), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('rifa')
    # ### end Alembic commands ###
