"""empty message

Revision ID: 459de96c7b01
Revises: ceb6f16ca95c
Create Date: 2026-02-03 20:22:59.180754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459de96c7b01'
down_revision = 'ceb6f16ca95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pagos', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('titular_zelle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contacto_zelle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('titular_transferencia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_ruta', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_cuenta', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.drop_column('numero_cuenta')
        batch_op.drop_column('numero_ruta')
        batch_op.drop_column('titular_transferencia')
        batch_op.drop_column('contacto_zelle')
        batch_op.drop_column('titular_zelle')
        batch_op.drop_column('metodo_pagos')

    # ### end Alembic commands ###
