"""empty message

Revision ID: 581951ea625c
Revises: b3d4872cb065
Create Date: 2026-02-06 05:42:58.554882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581951ea625c'
down_revision = 'b3d4872cb065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador_ticket', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
