"""empty message

Revision ID: a3fd187ce162
Revises: 2786fd419932
Create Date: 2026-02-03 06:24:36.277917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fd187ce162'
down_revision = '2786fd419932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('numero_ticket', sa.String(length=20), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprador_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('nombre_comprador', sa.String(length=100), nullable=False),
    sa.Column('email_comprador', sa.String(length=120), nullable=False),
    sa.Column('telefono_comprador', sa.String(length=20), nullable=True),
    sa.Column('comprobante_pago', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contrasena', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('admin')
        batch_op.drop_column('contrasena')
        batch_op.drop_column('foto_perfil')

    op.drop_table('comprador_ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
