"""empty message

Revision ID: b3d4872cb065
Revises: 5063514402bb
Create Date: 2026-02-06 01:53:49.302616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d4872cb065'
down_revision = '5063514402bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais_comprador', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador_ticket', schema=None) as batch_op:
        batch_op.drop_column('pais_comprador')

    # ### end Alembic commands ###
